obj-m += mirror_camera_diag.o
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2/sensor
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2/sensor/io
